### ISSUE TITLE
sandbox mode get error

### ISSUE THREAD

**Issue by andy08691** [nerds-odd-e/react-native-odde-alipay#1]
i want to use alipay in sandbox mode on Android, i have already use  "Alipay.useSandbox(true)", but still get "系統繁忙，請稍後再試", i don't know how to fix it, thanks

**Comment by JosephYao** [comment]
Hi Andy, 

Thank you for submitting this issue. Please let me know if you can read Chinese or not. I can go with both English and Chinese for further discussion. :)

According to the information you provided above, I suspect it's not an issue with this package but rather an issue with the data your sent to Alipay or the config. I used this module with my RN app just few days ago and the sandbox works well for me.

Here are two links for your reference. 

- https://blog.csdn.net/qq_36398455/article/details/77868188
- https://openclub.alipay.com/read.php?tid=543&fid=59

**Comment by andy08691** [comment]
Hi Joseph
這兩篇我都看過了，我有下載官方的Android app ，修改成sandbox模式，把後台生成訂單資訊丟過去是可以成功接起的！但是用RN sandbox 始終都出現"系統繁忙，請稍後再試", 也沒有出現error code(類似ALI40247)，我曾經試過帶空字串過去也是出現"系統繁忙，請稍後再試"，不曉得是我哪裡沒有寫好，感謝

**Comment by andy08691** [comment]
Hi Joseph
後來在這篇文章
http://jafeney.com/2016/11/16/2016-11-16-alipay/
發現我在AndroidManifest未把下列添加聲明
activity  
    android:name="com.alipay.sdk.app.H5PayActivity"  
    android:configChanges="orientation\|keyboardHidden\|navigation"  
    android:exported="false"  
    android:screenOrientation="behind" >
</activity
activity  
    android:name="com.alipay.sdk.auth.AuthActivity"  
    android:configChanges="orientation\|keyboardHidden\|navigation"  
    android:exported="false"  
    android:screenOrientation="behind" > 
</activity
感謝你的回答，目前已經解決問題了！

**Comment by JosephYao** [comment]
很高兴问题解决了。那篇文章我也看过的，写的不错。
